---
- block:
  - name: Create temporary download directory
    shell: mktemp -d
    register: tempdir_command_output

  - name: Determine path to temporary download directory
    set_fact:
      confluence_download_directory: "{{ tempdir_command_output.stdout }}"

  - name: Download Confluence archive
    get_url:
      url: "{{ confluence_installation_archive_url }}"
      checksum: "{{ confluence_installation_archive_checksum }}"
      dest: "{{ confluence_download_directory }}/{{ confluence_installation_archive_url | basename }}"

  - name: Extract Confluence archive
    unarchive:
      src: "{{ confluence_download_directory }}/{{ confluence_installation_archive_url | basename }}"
      dest: "{{ confluence_config_software_directory }}"
      copy: no
    notify: start confluence

  - name: Stat infos about Confluence installation directory
    stat:
      path: "{{ confluence_installation_instance_directory }}"
    register: confluence_installation_instance_stat

  - name: Fail if Confluence installation directory does not exist
    fail:
      msg: "Could not find confluence install directory at {{ confluence_installation_instance_directory }}"
    when: not confluence_installation_instance_stat.stat.exists

  - name: Copy JDBC driver to Confluence application if required
    when: confluence_installation_jdbc_driver_jar_source_path is defined and confluence_installation_jdbc_driver_jar_source_path != ""
    copy:
      remote_src: True
      src: "{{ confluence_installation_jdbc_driver_jar_source_path }}"
      dest: "{{ confluence_installation_instance_directory }}/lib/{{ confluence_installation_jdbc_driver_jar_source_path | basename }}"

  - name: Set user/group to root and disable write access for 'group' and 'other' in Confluence installation directory
    file:
      state: directory
      dest: "{{ confluence_installation_instance_directory }}"
      owner: root
      group: root
      mode: go-w
      recurse: yes

  - name: Set user/group to application user and mode to 0700 for logs,temp,work in Confluence installation directory
    file:
      state: directory
      dest: "{{ item }}"
      owner: "{{ confluence_user_name }}"
      group: root
      mode: 0700
    with_items:
    - "{{ confluence_installation_instance_directory }}/logs"
    - "{{ confluence_installation_instance_directory }}/temp"
    - "{{ confluence_installation_instance_directory }}/work"

- name: Configure Java for Confluence application
  template:
    src: usr/local/confluence/setenv.sh.j2
    dest: "{{ confluence_installation_instance_directory }}/bin/setenv.sh"
    owner: root
    group: root
    mode: 0644

- name: Configure CONF_USER for Confluence application
  template:
    src: usr/local/confluence/user.sh.j2
    dest: "{{ confluence_installation_instance_directory }}/bin/user.sh"
    owner: root
    group: root
    mode: 0644

- name: Configure CONF_HOME for Confluence application
  template:
    src: usr/local/confluence/confluence-init.properties.j2
    dest: "{{ confluence_installation_instance_directory }}/confluence/WEB-INF/classes/confluence-init.properties"
    owner: root
    group: root
    mode: 0644

  - name: Install init script for Confluence application
    template:
      src: etc/init.d/confluence.j2
      dest: /etc/init.d/{{ confluence_service_name }}
      owner: root
      group: root
      mode: 0755

  rescue:
  - name: Remove eventually inconsistent instance directory
    file:
      state: absent
      dest: "{{ confluence_installation_instance_directory }}"

  - name: Remove eventually inconsistent init script
    file:
      state: absent
      dest: "/etc/init.d/{{ confluence_service_name }}"

  always:
  - name: Remove temporary download directory
    file:
      state: absent
      dest: "{{ confluence_download_directory }}"
