---
- name: start confluence
  when: confluence_need_installation and confluence_start_after_installation
  service:
    name: "{{ confluence_service_name }}"
    state: started

- name: restart confluence
  when: not confluence_need_installation
  service:
    name: "{{ confluence_service_name }}"
    state: restarted
